version: '3'

services:
  db:
    image: postgres:9.6.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: kbase
      POSTGRES_USER: kbase
      POSTGRES_DB: kbase

  web:
    build: .
    hostname: web
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: knowledgebase.settings
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
