version: '3'

services:
  nginx:
    image: nginx:1.12.2
    command: bash -c "mkdir -p /code/logs/nginx/web/ && nginx -g 'daemon off;'"
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=8080
    volumes:
      - .:/code
      - ./nginx_docker.conf:/etc/nginx/conf.d/nginx_docker.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - web

  db:
    image: postgres:9.6.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: kbase
      POSTGRES_USER: kbase
      POSTGRES_DB: kbase

  web:
    build: .
    hostname: web
    restart: always
    command: uwsgi --ini /code/uwsgi.ini --py-autoreload 1
    environment:
      DJANGO_SETTINGS_MODULE: knowledgebase.settings
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
