version: '3'

services:
  nginx:
    image: nginx:1.12.2
    command: bash -c "mkdir -p /code/logs/nginx/web/ && nginx -g 'daemon off;'"
    volumes:
      - .:/code
      - ./nginx_docker.conf:/etc/nginx/conf.d/nginx_docker.conf:ro
    ports:
      - "8080:8080"
    depends_on:
      - web

  web:
    build: .
    hostname: web
    restart: always
    command: uwsgi --ini /code/uwsgi.ini
    environment:
      DJANGO_SETTINGS_MODULE: knowledgebase.settings
    volumes:
      - .:/code
    ports:
      - "8000:8000"
